---
language: python
python: "2.7"

sudo: required

env:
  - container=ubuntu-xenial
    role_name=softasap.sa-nginx-container


# whitelist
branches:
  only:
    - master
    - develop

services:
  - docker


# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - cd box-example/$(container)
  - make initialize
  - cd roles/${role_name}
  - git checkout $BRANCH
  - cd ../../
  - make build

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
