---
  # Portions come from https://github.com/ansible/nginx-container as the source of ideas

  - name: Container Setup | Install dumb init
    get_url:
      url: https://github.com/Yelp/dumb-init/releases/download/v{{ dumb_init_version }}/dumb-init_{{ dumb_init_version }}_amd64
      dest: /usr/bin/dumb-init
      owner: root
      group: root
      mode: 0775
    when: container_init == "dumb-init"  

  - name: Container Setup | Update container user
    user:
      name: "{{container_user}}"
      uid: "{{container_uid}}"
      group: root
      createhome: no

  - name: Container Setup | Nginx  | Create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0775
    with_items: "{{ nginx_directories }}"

  - name: Container Setup | Nginx  | Clear log files
    file:
      path: "/var/log/nginx/{{ item }}"
      state: absent 
    with_items:
      - access.log
      - error.log

  - name: "Container Setup | Nginx  | Make directories owned by {{ container_user }}:root"
    command: chown {{ container_user }}:root {{ item }}
    with_items:
      - "{{ nginx_pid_dir }}"
      - "{{ nginx_static_dir }}"
      - /var/log/nginx
      - /var/lib/nginx

  - name: Container Setup | Nginx  | Make directories writable by root group 
    command: chmod 775 {{ item }}
    with_items:
      - /var
      - /var/log
      - /var/lib 

  - name: "Container Setup | Nginx  | Make directories writable to {{ container_user }}:root" 
    command: chmod 775 {{ item }}
    with_items:
      - "{{ nginx_pid_dir }}"
      - "{{ nginx_static_dir }}"
      - /var/log/nginx
      - /var/lib/nginx

  - name: Container Setup | Nginx  | Link log files to stdout 
    command: "ln -sf /dev/stdout /var/log/nginx/{{ item }}"
    with_items:
      - access.log
      - error.log

  - name: Container Setup | Nginx  | Remove /var/cache/nginx, if it exists
    file:
      path: /var/cache/nginx
      state: absent

  - name: Container Setup | Nginx  | Create /var/cache/nginx
    file:
      path: /var/cache/nginx/client_temp
      state: directory
      owner: "{{ container_user }}"
      group: root
      mode: 0775
      recurse: yes
  
  - name: Container Setup | Nginx  | Create tmp directories with correct permissions
    file:
      path: "/var/lib/nginx/{{ item }}" 
      state: directory
      owner: "{{ container_user }}"
      group: root
      mode: 0775
    with_items:
      - tmp
      - tmp/client_body
      - tmp/fastcgi
      - tmp/proxy
      - tmp/scgi
      - tmp/uwsgi
