---
version: '2'
services:
  nginx:
    image: sa-nginx-container-www:latest
    ports:
    - 8000:8000
    volumes:
    - "${PWD}/app/conf/demo.conf:/etc/nginx/sites-enabled/demo.conf"
    - "${PWD}/app/www:/www"
