---
version: '3.1'
services:
  nginx:
    image: sa-nginx-container-www:latest
    ports:
    - 8000:8000
    command: ['/usr/bin/dumb-init', 'nginx', '-c', '/etc/nginx/nginx.conf']
#    volumes:
#    - "${PWD}/standalone-fallback/files/conf/demo.conf:/etc/nginx/sites-enabled/demo.conf"
#    - "${PWD}/standalone-fallback/files:/www"
